global:
  scrape_interval: 5s
  evaluation_interval: 5s

scrape_configs:
  # 抓取Prometheus自身指标
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']

  # 抓取电商项目指标
  - job_name: 'ecommerce-backend'
    static_configs:
      - targets: ['10.13.247.112:8083']  # 你的局域网IP
        labels: 
          application: 'ecommerce-backend'  
    metrics_path: '/actuator/prometheus'
    scrape_timeout: 10s